#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$PWD}"

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "OpenAI Realtime bridge mode needs OPENAI_API_KEY."
  echo "Run this first:"
  echo "  export OPENAI_API_KEY='replace-with-openai-api-key'"
  exit 1
fi

export LOCAL_REALTIME_ENGINE="${LOCAL_REALTIME_ENGINE:-openai-realtime}"
export LOCAL_REALTIME_STT="${LOCAL_REALTIME_STT:-openai-realtime}"
export LOCAL_REALTIME_CHAT_MODE="${LOCAL_REALTIME_CHAT_MODE:-openai-realtime}"
export LOCAL_REALTIME_SPEAK="${LOCAL_REALTIME_SPEAK:-off}"
export LOCAL_REALTIME_OPENAI_REALTIME_MODEL="${LOCAL_REALTIME_OPENAI_REALTIME_MODEL:-gpt-realtime-mini}"
export LOCAL_REALTIME_OPENAI_REALTIME_VOICE="${LOCAL_REALTIME_OPENAI_REALTIME_VOICE:-marin}"
export LOCAL_REALTIME_OPENAI_REALTIME_TOOLS="${LOCAL_REALTIME_OPENAI_REALTIME_TOOLS:-1}"
export LOCAL_REALTIME_OPENAI_REALTIME_TRANSCRIBE="${LOCAL_REALTIME_OPENAI_REALTIME_TRANSCRIBE:-0}"
export LOCAL_REALTIME_DELEGATION_MODE="${LOCAL_REALTIME_DELEGATION_MODE:-smart}"
export LOCAL_REALTIME_HANDOFF_ACK_SPEAK="${LOCAL_REALTIME_HANDOFF_ACK_SPEAK:-0}"
export LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO="${LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO:-1}"
export LOCAL_REALTIME_OPENAI_SUPPRESS_OUTPUT_ECHO="${LOCAL_REALTIME_OPENAI_SUPPRESS_OUTPUT_ECHO:-1}"
export LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS="${LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS:-350}"

exec "${SCRIPT_DIR}/run-codex-realtime-bridge.sh" "${TARGET_DIR}"
