#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$PWD}"

export LOCAL_REALTIME_STT="${LOCAL_REALTIME_STT:-local}"
export LOCAL_REALTIME_LOCAL_STT_MODEL="${LOCAL_REALTIME_LOCAL_STT_MODEL:-Xenova/whisper-medium.en}"
export LOCAL_REALTIME_LOCAL_STT_DTYPE="${LOCAL_REALTIME_LOCAL_STT_DTYPE:-q8}"
export LOCAL_REALTIME_LOCAL_STT_DEVICE="${LOCAL_REALTIME_LOCAL_STT_DEVICE:-cpu}"
export LOCAL_REALTIME_LOCAL_STT_SAMPLE_RATE="${LOCAL_REALTIME_LOCAL_STT_SAMPLE_RATE:-16000}"
export LOCAL_REALTIME_LOCAL_STT_LANGUAGE="${LOCAL_REALTIME_LOCAL_STT_LANGUAGE:-english}"
export LOCAL_REALTIME_LOCAL_STT_MIN_RMS="${LOCAL_REALTIME_LOCAL_STT_MIN_RMS:-90}"
export LOCAL_REALTIME_TRANSCRIPT_MODE="${LOCAL_REALTIME_TRANSCRIPT_MODE:-handoff-only}"

export LOCAL_REALTIME_SPEAK="${LOCAL_REALTIME_SPEAK:-kokoro}"
export LOCAL_REALTIME_KOKORO_VOICE="${LOCAL_REALTIME_KOKORO_VOICE:-af_heart}"
export LOCAL_REALTIME_KOKORO_DTYPE="${LOCAL_REALTIME_KOKORO_DTYPE:-q4}"

export LOCAL_REALTIME_DELEGATION_MODE="${LOCAL_REALTIME_DELEGATION_MODE:-smart}"
export LOCAL_REALTIME_CHAT_MODE="${LOCAL_REALTIME_CHAT_MODE:-canned}"

export LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO="${LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO:-1}"
export LOCAL_REALTIME_BARGE_IN_RMS="${LOCAL_REALTIME_BARGE_IN_RMS:-2200}"
export LOCAL_REALTIME_BARGE_IN_MIN_MS="${LOCAL_REALTIME_BARGE_IN_MIN_MS:-650}"
export LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS="${LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS:-1800}"
export LOCAL_REALTIME_VAD_RMS="${LOCAL_REALTIME_VAD_RMS:-240}"
export LOCAL_REALTIME_SILENCE_MS="${LOCAL_REALTIME_SILENCE_MS:-850}"
export LOCAL_REALTIME_MIN_AUDIO_MS="${LOCAL_REALTIME_MIN_AUDIO_MS:-500}"
export LOCAL_REALTIME_MAX_SPEECH_MS="${LOCAL_REALTIME_MAX_SPEECH_MS:-7000}"
export LOCAL_REALTIME_BACKEND_SPEECH_MAX_CHARS="${LOCAL_REALTIME_BACKEND_SPEECH_MAX_CHARS:-180}"

exec "${SCRIPT_DIR}/run-codex-realtime-bridge.sh" "${TARGET_DIR}"
