#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$PWD}"

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "OpenAI STT bridge mode needs OPENAI_API_KEY."
  echo "Run this first:"
  echo "  export OPENAI_API_KEY='replace-with-openai-api-key'"
  exit 1
fi

export LOCAL_REALTIME_STT="${LOCAL_REALTIME_STT:-openai}"
export LOCAL_REALTIME_TRANSCRIBE_MODEL="${LOCAL_REALTIME_TRANSCRIBE_MODEL:-gpt-4o-mini-transcribe}"
export LOCAL_REALTIME_TRANSCRIPT_MODE="${LOCAL_REALTIME_TRANSCRIPT_MODE:-handoff-only}"

export LOCAL_REALTIME_SPEAK="${LOCAL_REALTIME_SPEAK:-kokoro}"
export LOCAL_REALTIME_KOKORO_VOICE="${LOCAL_REALTIME_KOKORO_VOICE:-af_heart}"
export LOCAL_REALTIME_KOKORO_DTYPE="${LOCAL_REALTIME_KOKORO_DTYPE:-q4}"
export LOCAL_REALTIME_DELEGATION_MODE="${LOCAL_REALTIME_DELEGATION_MODE:-smart}"
export LOCAL_REALTIME_CHAT_MODE="${LOCAL_REALTIME_CHAT_MODE:-canned}"
export LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO="${LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO:-1}"
export LOCAL_REALTIME_BARGE_IN_RMS="${LOCAL_REALTIME_BARGE_IN_RMS:-2200}"
export LOCAL_REALTIME_BARGE_IN_MIN_MS="${LOCAL_REALTIME_BARGE_IN_MIN_MS:-650}"
export LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS="${LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS:-1800}"

exec "${SCRIPT_DIR}/run-codex-realtime-bridge.sh" "${TARGET_DIR}"
