#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ -z "${GEMINI_API_KEY:-${GOOGLE_API_KEY:-}}" ]]; then
  echo "Gemini Live needs an API key."
  echo "Run this first:"
  echo "  export GEMINI_API_KEY='replace-with-gemini-api-key'"
  exit 1
fi

if [[ "${LOCAL_REALTIME_SKIP_GEMINI_KEY_CHECK:-1}" != "1" ]]; then
  node --input-type=module - <<'NODE'
import { GoogleGenAI } from '@google/genai';

const apiKey =
  process.env.GEMINI_API_KEY ||
  process.env.GOOGLE_API_KEY ||
  process.env.GOOGLE_GENAI_API_KEY;

try {
  const ai = new GoogleGenAI({ apiKey });
  const pager = await ai.models.list({ config: { pageSize: 1 } });
  for await (const _model of pager) {
    break;
  }
} catch (error) {
  console.error("Gemini API key check failed. Export a valid GEMINI_API_KEY and restart.");
  console.error(String(error?.message || error).split("\n")[0]);
  process.exit(1);
}
NODE
fi

export LOCAL_REALTIME_ENGINE="${LOCAL_REALTIME_ENGINE:-gemini-live}"
export LOCAL_REALTIME_STT="${LOCAL_REALTIME_STT:-gemini-live}"
export LOCAL_REALTIME_CHAT_MODE="${LOCAL_REALTIME_CHAT_MODE:-gemini-live}"
export LOCAL_REALTIME_SPEAK="${LOCAL_REALTIME_SPEAK:-off}"
export LOCAL_REALTIME_GEMINI_MODEL="${LOCAL_REALTIME_GEMINI_MODEL:-gemini-3.1-flash-live-preview}"
export LOCAL_REALTIME_GEMINI_VOICE="${LOCAL_REALTIME_GEMINI_VOICE:-Aoede}"
export LOCAL_REALTIME_GEMINI_TOOLS="${LOCAL_REALTIME_GEMINI_TOOLS:-1}"
export LOCAL_REALTIME_GEMINI_VOICE_FOR_ALL="${LOCAL_REALTIME_GEMINI_VOICE_FOR_ALL:-1}"
export LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO="${LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO:-1}"
export LOCAL_REALTIME_GEMINI_ALLOW_BARGE_IN="${LOCAL_REALTIME_GEMINI_ALLOW_BARGE_IN:-1}"
export LOCAL_REALTIME_GEMINI_BARGE_IN_MODE="${LOCAL_REALTIME_GEMINI_BARGE_IN_MODE:-transcript}"
export LOCAL_REALTIME_GEMINI_BARGE_IN_RMS="${LOCAL_REALTIME_GEMINI_BARGE_IN_RMS:-4200}"
export LOCAL_REALTIME_GEMINI_STRONG_BARGE_IN_RMS="${LOCAL_REALTIME_GEMINI_STRONG_BARGE_IN_RMS:-8500}"
export LOCAL_REALTIME_GEMINI_BARGE_IN_FRAMES="${LOCAL_REALTIME_GEMINI_BARGE_IN_FRAMES:-6}"
export LOCAL_REALTIME_GEMINI_BARGE_IN_MIN_MS="${LOCAL_REALTIME_GEMINI_BARGE_IN_MIN_MS:-1500}"
export LOCAL_REALTIME_HANDOFF_ACK_SPEAK="${LOCAL_REALTIME_HANDOFF_ACK_SPEAK:-0}"
export LOCAL_REALTIME_SIDE_QUESTIONS_DURING_HANDOFF="${LOCAL_REALTIME_SIDE_QUESTIONS_DURING_HANDOFF:-1}"
export LOCAL_REALTIME_GEMINI_INPUT_GAIN="${LOCAL_REALTIME_GEMINI_INPUT_GAIN:-1.6}"
export LOCAL_REALTIME_GEMINI_AUDIO_PLAYBACK_MODE="${LOCAL_REALTIME_GEMINI_AUDIO_PLAYBACK_MODE:-codex}"
export LOCAL_REALTIME_GEMINI_AUDIO_GATE="${LOCAL_REALTIME_GEMINI_AUDIO_GATE:-0}"
export LOCAL_REALTIME_GEMINI_EXPLICIT_VAD="${LOCAL_REALTIME_GEMINI_EXPLICIT_VAD:-0}"
export LOCAL_REALTIME_GEMINI_SEND_STREAM_END="${LOCAL_REALTIME_GEMINI_SEND_STREAM_END:-0}"
export LOCAL_REALTIME_GEMINI_CONTEXT_SYNC="${LOCAL_REALTIME_GEMINI_CONTEXT_SYNC:-0}"
export LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS="${LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS:-600}"

exec "${SCRIPT_DIR}/run-codex-realtime-bridge.sh" "$@"
