#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_DIR="${1:-$PWD}"

if [[ -z "${GROQ_API_KEY:-${LOCAL_REALTIME_GROQ_API_KEY:-}}" ]]; then
  echo "Groq STT needs an API key."
  echo "Run this first:"
  echo "  export GROQ_API_KEY='replace-with-groq-api-key'"
  exit 1
fi

export LOCAL_REALTIME_STT="${LOCAL_REALTIME_STT:-groq}"
export LOCAL_REALTIME_GROQ_BASE_URL="${LOCAL_REALTIME_GROQ_BASE_URL:-https://api.groq.com/openai/v1}"
export LOCAL_REALTIME_GROQ_TRANSCRIBE_MODEL="${LOCAL_REALTIME_GROQ_TRANSCRIBE_MODEL:-whisper-large-v3-turbo}"
export LOCAL_REALTIME_GROQ_TRANSCRIBE_LANGUAGE="${LOCAL_REALTIME_GROQ_TRANSCRIBE_LANGUAGE:-en}"
export LOCAL_REALTIME_TRANSCRIPT_MODE="${LOCAL_REALTIME_TRANSCRIPT_MODE:-handoff-only}"

export LOCAL_REALTIME_DELEGATION_MODE="${LOCAL_REALTIME_DELEGATION_MODE:-smart}"
export LOCAL_REALTIME_CHAT_MODE="${LOCAL_REALTIME_CHAT_MODE:-canned}"

export LOCAL_REALTIME_SPEAK="${LOCAL_REALTIME_SPEAK:-kokoro}"
export LOCAL_REALTIME_KOKORO_VOICE="${LOCAL_REALTIME_KOKORO_VOICE:-af_heart}"
export LOCAL_REALTIME_KOKORO_DTYPE="${LOCAL_REALTIME_KOKORO_DTYPE:-q4}"

export LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO="${LOCAL_REALTIME_SUPPRESS_SPEAKER_ECHO:-1}"
export LOCAL_REALTIME_BARGE_IN_RMS="${LOCAL_REALTIME_BARGE_IN_RMS:-2200}"
export LOCAL_REALTIME_BARGE_IN_MIN_MS="${LOCAL_REALTIME_BARGE_IN_MIN_MS:-650}"
export LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS="${LOCAL_REALTIME_IGNORE_AFTER_SPEAK_MS:-1800}"
export LOCAL_REALTIME_VAD_RMS="${LOCAL_REALTIME_VAD_RMS:-300}"
export LOCAL_REALTIME_SILENCE_MS="${LOCAL_REALTIME_SILENCE_MS:-750}"
export LOCAL_REALTIME_MIN_AUDIO_MS="${LOCAL_REALTIME_MIN_AUDIO_MS:-450}"
export LOCAL_REALTIME_MAX_SPEECH_MS="${LOCAL_REALTIME_MAX_SPEECH_MS:-5000}"
export LOCAL_REALTIME_BACKEND_SPEECH_MAX_CHARS="${LOCAL_REALTIME_BACKEND_SPEECH_MAX_CHARS:-180}"

exec "${SCRIPT_DIR}/run-codex-realtime-bridge.sh" "${TARGET_DIR}"
